plugins {
    id 'com.android.application'
}

android {
    namespace 'com.avdbmini.android'

    compileSdk {
        version = release(37) {
            minorApiLevel = 1
        }
    }

    defaultConfig {
        applicationId 'com.avdbmini.android'

        // Android 8.0+
        minSdk 26

        // 暂时维持 36，不影响使用 compileSdk 37.1
        targetSdk 36

        versionCode 200
        versionName '2.0-gecko'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    packaging {
        jniLibs {
            useLegacyPackaging = true
        }

        resources {
            excludes += [
                'META-INF/DEPENDENCIES',
                'META-INF/LICENSE*',
                'META-INF/NOTICE*'
            ]
        }
    }
}

dependencies {
    implementation 'org.mozilla.geckoview:geckoview:156.0.20260921121718'
}
